version: '3'
networks:
  network:
    ipam:
      config:
        - subnet: 172.34.0.0/24
          gateway: 172.34.0.1

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      network:
        ipv4_address: 172.34.0.2

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      network:
        ipv4_address: 172.34.0.3

  corebankingservice:
    container_name: core-banking-service
    depends_on:
      - broker
    environment:
      KAFKA_ADDRESS: 172.34.0.3:29092
    build: 
      context: .
      dockerfile: CoreBankingService/Dockerfile
    networks:
      network:
        ipv4_address: 172.34.0.4
    
  moneylaunderingservice:
    container_name: money-laundering-service
    depends_on:
      - corebankingservice
    environment:
      KAFKA_ADDRESS: 172.34.0.3:29092
    build: 
      context: .
      dockerfile: MoneyLaunderingService/Dockerfile
    networks:
      network:
        ipv4_address: 172.34.0.5
    
  transactionanalyticsservice:
    container_name: transaction-analytics-service
    depends_on:
      - moneylaunderingservice
    environment:
      KAFKA_ADDRESS: 172.34.0.3:29092
    build: 
      context: .
      dockerfile: TransactionAnalyticsService/Dockerfile
    networks:
      network:
        ipv4_address: 172.34.0.6